spring:
  application:
    name: yoremo
  profiles:
    include: secrets

  threads:
    virtual:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

adapter:
  http:
    json-place-holder:
      base-url: https://jsonplaceholder.typicode.com
