spring:
  application:
    name: yoremo
  profiles:
    include: secrets
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      format_sql: true

  ai:
    openai:
      api-key: ${spring.ai.openai.api-key}

adapter:
  http:
    json-placeholder:
      base-url: https://jsonplaceholder.typicode.com
