spring:
  application:
    name: yoremo
  profiles:
    include: secrets

  threads:
    virtual:
      enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      format_sql: true

adapter:
  http:
    json-place-holder:
      base-url: https://jsonplaceholder.typicode.com
