spring:
  application:
    name: yoremo
  profiles:
    include: secrets
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      format_sql: true

  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
        schema-validation: true
    chat:
      client:
        enabled: true
    openai:
      api-key: ${spring.ai.openai.api-key}
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4o

adapter:
  http:
    json-placeholder:
      base-url: https://jsonplaceholder.typicode.com
